fix:popup #175
devvsakib/github-error-solve pull request #176
Opened 2023-10-04 05:59 UTC by A-Kashif108

2023-10-04 06:00 UTC, A-Kashif108 commented
fix #175

2023-10-04 06:05 UTC, devvsakib requested changes
It's closing the popup even if I click on popup!!

2023-10-04 15:38 UTC, A-Kashif108 commented
Check now

2023-10-05 04:25 UTC, devvsakib approved these changes
Great, Happy Coding

2023-10-05 04:26 UTC, merged